FROM maven:3.9-eclipse-temurin-17 AS build

WORKDIR /app
COPY pom.xml .
COPY src ./src

RUN mvn clean package

FROM tomcat:9.0

COPY --from=build /app/target/AI-OLMS.war /usr/local/tomcat/webapps/

EXPOSE 8080

###
docker build -t ai-olms:latest .
docker run -d -p 7012:8080 ai-olms:latest